// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TaskManager.DataAccessLayer;

namespace TaskManager.DataAccessLayer.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20180611104806_rmod PreTaskId")]
    partial class rmodPreTaskId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskManager.Model.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Task_Id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("End_Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Task")
                        .HasMaxLength(100);

                    b.Property<int?>("ParentId");

                    b.Property<int>("Priority");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("Start_Date");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("TaskManager.Model.Task", b =>
                {
                    b.HasOne("TaskManager.Model.Task", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
